In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from numpy import loadtxt, savetxt
from sklearn.metrics import classification_report, confusion_matrix
from sklearn import preprocessing
from sklearn.ensemble import ExtraTreesClassifier
import scikitplot
from scikitplot.metrics import plot_roc_curve
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import cross_val_score,cross_validate, train_test_split, GridSearchCV
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error

In [2]:
y = np.loadtxt("kmeanpredict.csv", delimiter=",")
dataset = pd.read_csv(r'C:\Users\rishi\Desktop\FinalDataset.csv')
data = dataset.copy()
data = pd.DataFrame(data)
print(data.head())
data.columns = ['Age', 'Brush', 'Ball', 'Watch', 'Mobile', 'Duster']
X = data[['Age', 'Brush', 'Ball', 'Watch', 'Mobile', 'Duster']].to_numpy()
(unique, counts) = np.unique(y, return_counts=True)
frequencies = np.asarray((unique, counts)).T
print(frequencies)
print(y)

   Age  Brush  Ball  Watch  Mobile  Duster
0    2   3.00  2.02   1.40    3.02    1.78
1    2   2.61  2.51   5.57    2.26    2.34
2    2  10.56  4.42  12.62    8.69   18.76
3    2   3.05  2.89   3.13    3.49    3.22
4    2   3.12  3.82   2.74    1.73    1.41
[[  0. 112.]
 [  1.  37.]]
[0. 1. 1. 0. 0. 0. 0. 1. 1. 0. 1. 0. 0. 0. 0. 1. 1. 1. 1. 1. 0. 0. 1. 1.
 0. 1. 0. 1. 1. 1. 0. 0. 0. 1. 1. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0.
 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 1. 0. 0.
 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 1. 0. 1. 1. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.
 1. 0. 0. 0. 0.]


In [3]:
total = np.empty(0,dtype = float)
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size = 0.25)
(unique, counts) = np.unique(y_train, return_counts=True)
frequencies = np.asarray((unique, counts)).T
(unique, counts) = np.unique(y_test, return_counts=True)
frequencies2 = np.asarray((unique, counts)).T
print(frequencies)
print(frequencies2)
scaler = preprocessing.StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
parameters = {'solver': ['lbfgs'], 'activation': ['logistic'], 'max_iter': [100], 'alpha': [0.1], 'hidden_layer_sizes':(10,)}
clf = GridSearchCV(MLPClassifier(), parameters, n_jobs=-1, refit = True, verbose=2, cv=9)
clf.fit(X_train, y_train)
print(clf.best_estimator_)
total = np.append(total,clf.best_score_)
print(clf.best_estimator_)
print(total)
print(np.mean(total)*100)
clf_predictions = clf.predict(X_test)
#grid_prob = grid.predict_proba(X_test)
print(confusion_matrix(y_test,clf_predictions).ravel())
print(classification_report(y_test,clf_predictions,digits = 5))


[[ 0. 82.]
 [ 1. 29.]]
[[ 0. 30.]
 [ 1.  8.]]
Fitting 9 folds for each of 1 candidates, totalling 9 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.


MLPClassifier(activation='logistic', alpha=0.1, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=10, learning_rate='constant',
              learning_rate_init=0.001, max_iter=100, momentum=0.9,
              n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
              random_state=None, shuffle=True, solver='lbfgs', tol=0.0001,
              validation_fraction=0.1, verbose=False, warm_start=False)
MLPClassifier(activation='logistic', alpha=0.1, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=10, learning_rate='constant',
              learning_rate_init=0.001, max_iter=100, momentum=0.9,
              n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
              random_state=None, shuffle=True, solver='lbfgs', tol=0.0001,
              validation_fraction=0.1, verbose=False, warm_start=False)
[0.9819819

[Parallel(n_jobs=-1)]: Done   4 out of   9 | elapsed:    2.8s remaining:    3.6s
[Parallel(n_jobs=-1)]: Done   9 out of   9 | elapsed:    2.8s remaining:    0.0s
[Parallel(n_jobs=-1)]: Done   9 out of   9 | elapsed:    2.8s finished
C:\Users\rishi\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:814: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


In [4]:
clf1 = MLPClassifier(activation='logistic', alpha=0.1, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=10, learning_rate='constant',
              learning_rate_init=0.001, max_iter=100, momentum=0.9,
              n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
              random_state=None, shuffle=True, solver='lbfgs', tol=0.0001,
              validation_fraction=0.1, verbose=False, warm_start=False)
clf1.fit(X_train, y_train)
y_pred = clf1.predict(X_test)
print(clf1.score(X_test,y_test))
scaler = preprocessing.StandardScaler()
data_scaled = scaler.fit_transform(X)
scores = cross_val_score(clf1, data_scaled, y, cv=9)
print(scores)
final = np.mean(scores)
print(final*100)

0.9736842105263158
[0.94444444 1.         1.         1.         0.9375     1.
 1.         1.         1.        ]
98.68827160493827


In [5]:
# total = np.empty(0,dtype = float)
# for i in range(0,10):
#     X_train, X_test, y_train, y_test = train_test_split(X, y,test_size = 0.25,random_state = i)
#     (unique, counts) = np.unique(y_train, return_counts=True)
#     frequencies = np.asarray((unique, counts)).T
#     (unique, counts) = np.unique(y_test, return_counts=True)
#     frequencies2 = np.asarray((unique, counts)).T
#     print(frequencies)
#     print(frequencies2)
#     scaler = preprocessing.StandardScaler()
#     X_train = scaler.fit_transform(X_train)
#     X_test = scaler.transform(X_test)
#     parameters = {'solver': ['sgd'],'batch_size': [27], 'learning_rate_init': 10.0 ** -np.arange(1, 5),'activation': ['identity'], 'max_iter': [50,100,200,300,400,500], 'alpha': 10.0 ** -np.arange(1, 6), 'hidden_layer_sizes':(10,)}
#     clf = GridSearchCV(MLPClassifier(), parameters, n_jobs=-1,refit = True, verbose=2, cv = 4)
#     clf.fit(X_train, y_train)
#     print(clf.best_estimator_)
#     total = np.append(total,clf.best_score_)

# print(total)
# print(np.mean(total)*100)
# clf_predictions = clf.predict(X_test)
# #grid_prob = grid.predict_proba(X_test)
# print(confusion_matrix(y_test,clf_predictions).ravel())
# print(classification_report(y_test,clf_predictions))



In [6]:
# clf = MLPClassifier(activation='tanh', alpha=0.01, batch_size=27, beta_1=0.9,
#               beta_2=0.999, early_stopping=False, epsilon=1e-08,
#               hidden_layer_sizes=10, learning_rate='constant',
#               learning_rate_init=0.1, max_iter=100, momentum=0.9,
#               n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
#               shuffle=True, solver='sgd', tol=0.0001, random_state = 3,
#               validation_fraction=0.1, verbose=False, warm_start=False)
# for i in range(3,11):
#     scores = cross_val_score(clf, X, y, n_jobs = -1, verbose = True, cv = i)
#     print(scores)
#     final = np.mean(scores)
#     print(final)