In [1]:
from sklearn import svm
from random import randrange
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from numpy import loadtxt, savetxt
from sklearn.cluster import KMeans
from sklearn.model_selection import cross_validate
from sklearn.naive_bayes import BernoulliNB
from sklearn.model_selection import GridSearchCV
import seaborn as sns
from sklearn.svm import SVC
from sklearn.metrics import precision_recall_fscore_support
from sklearn.metrics import classification_report, confusion_matrix
from sklearn import preprocessing
from sklearn.ensemble import ExtraTreesClassifier
import scikitplot
from scikitplot.metrics import plot_roc_curve
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error

In [2]:
y = np.loadtxt("kmeanpredict.csv", delimiter=",")
dataset = pd.read_csv(r'C:\Users\rishi\Desktop\FinalDataset.csv')
data = dataset.copy()
data = pd.DataFrame(data)
print(data.head())
data.columns = ['Age', 'Brush', 'Ball', 'Watch', 'Mobile', 'Duster']
X = data[['Age', 'Brush', 'Ball', 'Watch', 'Mobile', 'Duster']].to_numpy()
(unique, counts) = np.unique(y, return_counts=True)
frequencies = np.asarray((unique, counts)).T
print(frequencies)
print(y)

   Age  Brush  Ball  Watch  Mobile  Duster
0    2   3.00  2.02   1.40    3.02    1.78
1    2   2.61  2.51   5.57    2.26    2.34
2    2  10.56  4.42  12.62    8.69   18.76
3    2   3.05  2.89   3.13    3.49    3.22
4    2   3.12  3.82   2.74    1.73    1.41
[[  0. 112.]
 [  1.  37.]]
[0. 1. 1. 0. 0. 0. 0. 1. 1. 0. 1. 0. 0. 0. 0. 1. 1. 1. 1. 1. 0. 0. 1. 1.
 0. 1. 0. 1. 1. 1. 0. 0. 0. 1. 1. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0.
 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 1. 0. 0.
 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 1. 0. 1. 1. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.
 1. 0. 0. 0. 0.]


In [3]:
X_train, X_test, y_train, y_test = train_test_split(X, y)
(unique, counts) = np.unique(y_train, return_counts=True)
frequencies = np.asarray((unique, counts)).T
(unique, counts) = np.unique(y_test, return_counts=True)
frequencies2 = np.asarray((unique, counts)).T
print(frequencies)
print(frequencies2)
scaler = preprocessing.StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


[[ 0. 88.]
 [ 1. 23.]]
[[ 0. 24.]
 [ 1. 14.]]


In [4]:
clf = SVC(C=10, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=1, kernel='linear',
    max_iter=-1, probability=True, random_state=None, shrinking=True, tol=0.001,
    verbose=False)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
print(clf.score(X_test,y_test))
scores = cross_val_score(clf, X, y, cv=9)
print(scores)
final = np.mean(scores)
print(final*100)

1.0
[0.94444444 1.         0.94117647 0.94117647 0.9375     1.
 1.         1.         1.        ]
97.3810820624546


In [5]:

#scaler = MinMaxScaler() 
#data_scaled = scaler.fit_transform(X)
scaler = preprocessing.StandardScaler()
data_scaled = scaler.fit_transform(X)
clf1 = SVC(C=10, cache_size=200, class_weight=None, coef0=0.0,
            decision_function_shape='ovr', degree=3, gamma=1, kernel='linear',
            max_iter=-1, probability=True, random_state=None, shrinking=True, tol=0.001,
            verbose=False)
scores = cross_val_score(clf1, data_scaled, y, cv=9)
print(scores)
final = np.mean(scores)
print(final*100)

[0.94444444 1.         0.94117647 1.         0.9375     0.9375
 1.         1.         1.        ]
97.34023238925201
